# Changes here will be overwritten by Copier
_commit: 0.1.0-8-g940082e
_src_path: https://github.com/fastapi-mvc/copier-generator
copyright_date: 2022
generator: project
generator_name: project
license: MIT
nix: true
repo_url: https://github.com/fastapi-mvc/copier-project
